<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>Peter Waher</Authors>
    <Company>Trust Anchor Group AB</Company>
    <Product>IdApp</Product>
    <Description>NFC Abstraction Layer for the TAG ID App</Description>
    <Copyright>Copyright © Trust Anchor Group 2022-2026. All rights reserved.</Copyright>
    <RepositoryUrl>https://github.com/Trust-Anchor-Group/IdApp</RepositoryUrl>
    <NeutralLanguage>English</NeutralLanguage>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.5" />
    <PackageReference Include="Waher.Content" Version="3.4.7" />
	  <PackageReference Include="Waher.Networking" Version="4.6.5" />
	  <PackageReference Include="Waher.Runtime.Settings" Version="1.2.1" />
	  <PackageReference Include="Waher.Security" Version="1.2.0" />
	  <PackageReference Include="Waher.Security.EllipticCurves" Version="1.5.3" />
	  <PackageReference Include="Waher.Security.SHA3" Version="1.2.2" />
  </ItemGroup>

</Project>
