//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuroAccessMaui.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuroAccessMaui.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name {0} is already taken. Choose another..
        /// </summary>
        internal static string AccountNameAlreadyTaken {
            get {
                return ResourceManager.GetString("AccountNameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A peer review you requested has been accepted..
        /// </summary>
        internal static string APeerReviewYouhaveRequestedHasBeenAccepted {
            get {
                return ResourceManager.GetString("APeerReviewYouhaveRequestedHasBeenAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A peer review you requested has been rejected, due to a signature error..
        /// </summary>
        internal static string APeerYouRequestedToReviewHasBeenRejectedDueToSignatureError {
            get {
                return ResourceManager.GetString("APeerYouRequestedToReviewHasBeenRejectedDueToSignatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A peer you requested to review your application, has rejected to approve it..
        /// </summary>
        internal static string APeerYouRequestedToReviewHasRejected {
            get {
                return ResourceManager.GetString("APeerYouRequestedToReviewHasRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A petition has been sent to the parts of the contract. If any of the parts accepts the petition, the contract information will be displayed on the screen..
        /// </summary>
        internal static string APetitionHasBeenSentToTheContract {
            get {
                return ResourceManager.GetString("APetitionHasBeenSentToTheContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A petition has been sent to the owner of the identity. If the owner accepts the petition, the identity information will be displayed on the screen..
        /// </summary>
        internal static string APetitionHasBeenSentToTheOwner {
            get {
                return ResourceManager.GetString("APetitionHasBeenSentToTheOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A petition has been sent to your peer.
        /// </summary>
        internal static string APetitionHasBeenSentToYourPeer {
            get {
                return ResourceManager.GetString("APetitionHasBeenSentToYourPeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App is not connected to the network..
        /// </summary>
        internal static string AppNotConnected {
            get {
                return ResourceManager.GetString("AppNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this contact from your list of contacts?.
        /// </summary>
        internal static string AreYouSureYouWantToRemoveContact {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRemoveContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to report your legal identity as compromised, stolen or hacked?.
        /// </summary>
        internal static string AreYouSureYouWantToReportYourLegalIdentityAsCompromized {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToReportYourLegalIdentityAsCompromized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to revoke your legal identity from the application?.
        /// </summary>
        internal static string AreYouSureYouWantToRevokeYourLegalIdentity {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRevokeYourLegalIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to transfer your legal identity from the application to another? The identity will be removed from this device once completed. Also make sure no-one else can see your screen during the process..
        /// </summary>
        internal static string AreYouSureYouWantToTransferYourLegalIdentity {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToTransferYourLegalIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to {0}.
        /// </summary>
        internal static string CantConnectTo {
            get {
                return ResourceManager.GetString("CantConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response not returned within configured time..
        /// </summary>
        internal static string ClientMessageAuthenticationTimeout {
            get {
                return ResourceManager.GetString("ClientMessageAuthenticationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code does not match..
        /// </summary>
        internal static string ClientMessageCountryCodeMismatch {
            get {
                return ResourceManager.GetString("ClientMessageCountryCodeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code not verified..
        /// </summary>
        internal static string ClientMessageCountryCodeNotVerified {
            get {
                return ResourceManager.GetString("ClientMessageCountryCodeNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name not verified..
        /// </summary>
        internal static string ClientMessageFirstNameNotVerified {
            get {
                return ResourceManager.GetString("ClientMessageFirstNameNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name not verified..
        /// </summary>
        internal static string ClientMessageLastNameNotVerified {
            get {
                return ResourceManager.GetString("ClientMessageLastNameNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity not valid..
        /// </summary>
        internal static string ClientMessageNotValid {
            get {
                return ResourceManager.GetString("ClientMessageNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Number does not match..
        /// </summary>
        internal static string ClientMessagePersonalNumberMismatch {
            get {
                return ResourceManager.GetString("ClientMessagePersonalNumberMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal number not verified..
        /// </summary>
        internal static string ClientMessagePersonalNumberNotVerified {
            get {
                return ResourceManager.GetString("ClientMessagePersonalNumberNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned reference did not match request reference..
        /// </summary>
        internal static string ClientMessageReferenceMismatch {
            get {
                return ResourceManager.GetString("ClientMessageReferenceMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document information not returned as expected..
        /// </summary>
        internal static string ClientMessageUnexpectedDocumentInformation {
            get {
                return ResourceManager.GetString("ClientMessageUnexpectedDocumentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event result not returned as expected..
        /// </summary>
        internal static string ClientMessageUnexpectedEventResult {
            get {
                return ResourceManager.GetString("ClientMessageUnexpectedEventResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected response returned..
        /// </summary>
        internal static string ClientMessageUnexpectedResult {
            get {
                return ResourceManager.GetString("ClientMessageUnexpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code not recognized..
        /// </summary>
        internal static string CodeNotRecognized {
            get {
                return ResourceManager.GetString("CodeNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not follow the ubiquitous encryption policy.
        /// </summary>
        internal static string DomainDoesNotFollowEncryptionPolicy {
            get {
                return ResourceManager.GetString("DomainDoesNotFollowEncryptionPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid operator.
        /// </summary>
        internal static string DomainIsNotAValidOperator {
            get {
                return ResourceManager.GetString("DomainIsNotAValidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to bind viewmodel {0} for page {1}.
        /// </summary>
        internal static string FailedToBindViewModelForPage {
            get {
                return ResourceManager.GetString("FailedToBindViewModelForPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to close page.
        /// </summary>
        internal static string FailedToClosePage {
            get {
                return ResourceManager.GetString("FailedToClosePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to navigate to page {0}  {1}.
        /// </summary>
        internal static string FailedToNavigateToPage {
            get {
                return ResourceManager.GetString("FailedToNavigateToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restore state for viewmodel {0} for page {1}.
        /// </summary>
        internal static string FailedToRestoreViewModelStateForPage {
            get {
                return ResourceManager.GetString("FailedToRestoreViewModelStateForPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save state for viewmodel {0} for page {1}.
        /// </summary>
        internal static string FailedToSaveViewModelStateForPage {
            get {
                return ResourceManager.GetString("FailedToSaveViewModelStateForPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unbind viewmodel {0} for page {1}.
        /// </summary>
        internal static string FailedToUnbindViewModelForPage {
            get {
                return ResourceManager.GetString("FailedToUnbindViewModelForPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file upload service found on broker..
        /// </summary>
        internal static string FileUploadServiceNotFound {
            get {
                return ResourceManager.GetString("FileUploadServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A link to the ID was copied to the clipboard..
        /// </summary>
        internal static string IdCopiedSuccessfully {
            get {
                return ResourceManager.GetString("IdCopiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string IdentityState_Approved {
            get {
                return ResourceManager.GetString("IdentityState_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compromised.
        /// </summary>
        internal static string IdentityState_Compromised {
            get {
                return ResourceManager.GetString("IdentityState_Compromised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string IdentityState_Created {
            get {
                return ResourceManager.GetString("IdentityState_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsoleted.
        /// </summary>
        internal static string IdentityState_Obsoleted {
            get {
                return ResourceManager.GetString("IdentityState_Obsoleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string IdentityState_Rejected {
            get {
                return ResourceManager.GetString("IdentityState_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TAG Signature URI..
        /// </summary>
        internal static string InvalidTagSignatureId {
            get {
                return ResourceManager.GetString("InvalidTagSignatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal ID not approved..
        /// </summary>
        internal static string LegalIdNotApproved {
            get {
                return ResourceManager.GetString("LegalIdNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No legal service found on broker..
        /// </summary>
        internal static string LegalServiceNotFound {
            get {
                return ResourceManager.GetString("LegalServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (me).
        /// </summary>
        internal static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Legal ID selected..
        /// </summary>
        internal static string NoLegalIdSelected {
            get {
                return ResourceManager.GetString("NoLegalIdSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name you want to use for your account.
        /// </summary>
        internal static string OnboardingAccountPageDetails {
            get {
                return ResourceManager.GetString("OnboardingAccountPageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string OnboardingAccountPageTitle {
            get {
                return ResourceManager.GetString("OnboardingAccountPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll send you a verification code.
        /// </summary>
        internal static string OnboardingEmailPageDetails {
            get {
                return ResourceManager.GetString("OnboardingEmailPageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify email.
        /// </summary>
        internal static string OnboardingEmailPageTitle {
            get {
                return ResourceManager.GetString("OnboardingEmailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get verified, you need to enter your phone number.
        /// </summary>
        internal static string OnboardingPhonePageDetails {
            get {
                return ResourceManager.GetString("OnboardingPhonePageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started.
        /// </summary>
        internal static string OnboardingPhonePageTitle {
            get {
                return ResourceManager.GetString("OnboardingPhonePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDEFINED.
        /// </summary>
        internal static string OnboardingProviderPageDetails {
            get {
                return ResourceManager.GetString("OnboardingProviderPageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected provider.
        /// </summary>
        internal static string OnboardingProviderPageTitle {
            get {
                return ResourceManager.GetString("OnboardingProviderPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose in what context you intend to use the Neuro-Access.
        /// </summary>
        internal static string OnboardingPurposePageDetails {
            get {
                return ResourceManager.GetString("OnboardingPurposePageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string OnboardingPurposePageTitle {
            get {
                return ResourceManager.GetString("OnboardingPurposePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator {0} does not support registration of new accounts.
        /// </summary>
        internal static string OperatorDoesNotSupportRegisteringNewAccounts {
            get {
                return ResourceManager.GetString("OperatorDoesNotSupportRegisteringNewAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer review accepted.
        /// </summary>
        internal static string PeerReviewAccepted {
            get {
                return ResourceManager.GetString("PeerReviewAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer review rejected.
        /// </summary>
        internal static string PeerReviewRejected {
            get {
                return ResourceManager.GetString("PeerReviewRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition sent.
        /// </summary>
        internal static string PetitionSent {
            get {
                return ResourceManager.GetString("PetitionSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition to view contract was denied..
        /// </summary>
        internal static string PetitionToViewContractWasDenied {
            get {
                return ResourceManager.GetString("PetitionToViewContractWasDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition to view legal identity was denied..
        /// </summary>
        internal static string PetitionToViewLegalIdentityWasDenied {
            get {
                return ResourceManager.GetString("PetitionToViewLegalIdentityWasDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN has been successfully changed..
        /// </summary>
        internal static string PinChanged {
            get {
                return ResourceManager.GetString("PinChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PIN must not contain any word from the identity address lines..
        /// </summary>
        internal static string PinContainsAddress {
            get {
                return ResourceManager.GetString("PinContainsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PIN must not contain the identity e-mail address..
        /// </summary>
        internal static string PinContainsEMail {
            get {
                return ResourceManager.GetString("PinContainsEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PIN must not contain any word from the identity names..
        /// </summary>
        internal static string PinContainsName {
            get {
                return ResourceManager.GetString("PinContainsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PIN must not contain the identity personal number..
        /// </summary>
        internal static string PinContainsPersonalNumber {
            get {
                return ResourceManager.GetString("PinContainsPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PIN must not contain the identity phone number..
        /// </summary>
        internal static string PinContainsPhoneNumber {
            get {
                return ResourceManager.GetString("PinContainsPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN is invalid. You have {0} remaining attempts..
        /// </summary>
        internal static string PinIsInvalid {
            get {
                return ResourceManager.GetString("PinIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN attempts entering is exceded. Your application has been blocked till {0}..
        /// </summary>
        internal static string PinIsInvalidAplicationBlocked {
            get {
                return ResourceManager.GetString("PinIsInvalidAplicationBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN attempts entering is exceded. Your application has been blocked forever.
        /// </summary>
        internal static string PinIsInvalidAplicationBlockedForever {
            get {
                return ResourceManager.GetString("PinIsInvalidAplicationBlockedForever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN attempts entering is exceded. Your application has been blocked for one week.
        /// </summary>
        internal static string PinIsInvalidAplicationBlockedForOneWeek {
            get {
                return ResourceManager.GetString("PinIsInvalidAplicationBlockedForOneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN attempts entering is exceded. Your application has been blocked till tomorrow at {0}..
        /// </summary>
        internal static string PinIsInvalidAplicationBlockedTillTomorrow {
            get {
                return ResourceManager.GetString("PinIsInvalidAplicationBlockedTillTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN length must be at least {0} characters..
        /// </summary>
        internal static string PinTooShort {
            get {
                return ResourceManager.GetString("PinTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least {0} letters, digits or symbols must be used..
        /// </summary>
        internal static string PinWithNotEnoughDigitsLettersSigns {
            get {
                return ResourceManager.GetString("PinWithNotEnoughDigitsLettersSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must also use at least {0} digits or symbols..
        /// </summary>
        internal static string PinWithNotEnoughDigitsOrSigns {
            get {
                return ResourceManager.GetString("PinWithNotEnoughDigitsOrSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must also use at least {0} letters or digits..
        /// </summary>
        internal static string PinWithNotEnoughLettersOrDigits {
            get {
                return ResourceManager.GetString("PinWithNotEnoughLettersOrDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must also use at least {0} letters or symbols..
        /// </summary>
        internal static string PinWithNotEnoughLettersOrSigns {
            get {
                return ResourceManager.GetString("PinWithNotEnoughLettersOrSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PIN must not contain more than {0} identical symbols..
        /// </summary>
        internal static string PinWithTooManyIdenticalSymbols {
            get {
                return ResourceManager.GetString("PinWithTooManyIdenticalSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PIN must not contain more than {0} sequenced symbols, e.g. &quot;12&quot; or &quot;ab&quot;..
        /// </summary>
        internal static string PinWithTooManySequencedSymbols {
            get {
                return ResourceManager.GetString("PinWithTooManySequencedSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review all information above, and check the corresponding check boxes if the information is correct. This must be done before you can approve the information..
        /// </summary>
        internal static string PleaseReviewAndCheckAllCheckboxes {
            get {
                return ResourceManager.GetString("PleaseReviewAndCheckAllCheckboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational use.
        /// </summary>
        internal static string PurposeEducational {
            get {
                return ResourceManager.GetString("PurposeEducational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows you to use Tag ID for educational purposes. You can use the app to sign or access resources as a private person, either as an educator, or as a student. The account may be limited in time. The account may also be removed when no longer used. Check with the service provider for more information..
        /// </summary>
        internal static string PurposeEducationalDescription {
            get {
                return ResourceManager.GetString("PurposeEducationalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental use.
        /// </summary>
        internal static string PurposeExperimental {
            get {
                return ResourceManager.GetString("PurposeExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows you to use Tag ID for experimental purposes. You can use the app to sign or access resources as a private person, with the goal of learning the technology and for what purposes it can be used. The account may be limited in time. The account may also be removed when no longer used. Check with the service provider for more information..
        /// </summary>
        internal static string PurposeExperimentalDescription {
            get {
                return ResourceManager.GetString("PurposeExperimentalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal use.
        /// </summary>
        internal static string PurposePersonal {
            get {
                return ResourceManager.GetString("PurposePersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows you to use Tag ID for personal purposes. You can use the app to sign or access resources as a private person. Certain operations may incur costs, depending on the service provider you choose. Check with the service provider for more information..
        /// </summary>
        internal static string PurposePersonalDescription {
            get {
                return ResourceManager.GetString("PurposePersonalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose access purpose .
        /// </summary>
        internal static string PurposesSectionTitle {
            get {
                return ResourceManager.GetString("PurposesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work use.
        /// </summary>
        internal static string PurposeWork {
            get {
                return ResourceManager.GetString("PurposeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows you to use Tag ID for work purposes. This includes work not for profit in organizations. You can use the app to sign or access resources as a representative of an organization. Certain operations may incur costs, depending on the service provider you choose. Check with the service provider for more information..
        /// </summary>
        internal static string PurposeWorkDescription {
            get {
                return ResourceManager.GetString("PurposeWorkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code not understood.
        /// </summary>
        internal static string QrCodeNotUnderstood {
            get {
                return ResourceManager.GetString("QrCodeNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An inconsistency in the internal database has been detected. This can happen if the app is not closed properly. The app will therefore close. The next time you start the app, the database will be repaired..
        /// </summary>
        internal static string RepairRestart {
            get {
                return ResourceManager.GetString("RepairRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request timed out.
        /// </summary>
        internal static string RequestTimedOut {
            get {
                return ResourceManager.GetString("RequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was cancelled.
        /// </summary>
        internal static string RequestWasCancelled {
            get {
                return ResourceManager.GetString("RequestWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned QR Code.
        /// </summary>
        internal static string ScannedQrCode {
            get {
                return ResourceManager.GetString("ScannedQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature petition was denied..
        /// </summary>
        internal static string SignaturePetitionDenied {
            get {
                return ResourceManager.GetString("SignaturePetitionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRING NOT DEFINED.
        /// </summary>
        internal static string STRINGNOTDEFINED {
            get {
                return ResourceManager.GetString("STRINGNOTDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Engraved with link to {0}..
        /// </summary>
        internal static string TagEngraved {
            get {
                return ResourceManager.GetString("TagEngraved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to engrave tag with link to {0}..
        /// </summary>
        internal static string TagNotEngraved {
            get {
                return ResourceManager.GetString("TagNotEngraved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag value copied to clipboard.
        /// </summary>
        internal static string TagValueCopiedToClipboard {
            get {
                return ResourceManager.GetString("TagValueCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no network.
        /// </summary>
        internal static string ThereIsNoNetwork {
            get {
                return ResourceManager.GetString("ThereIsNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code represents a Tag ID invitation, and cannot be claimed at this time..
        /// </summary>
        internal static string ThisCodeCannotBeClaimedAtThisTime {
            get {
                return ResourceManager.GetString("ThisCodeCannotBeClaimedAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate with {0}.
        /// </summary>
        internal static string UnableToAuthenticateWith {
            get {
                return ResourceManager.GetString("UnableToAuthenticateWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change network password..
        /// </summary>
        internal static string UnableToChangePassword {
            get {
                return ResourceManager.GetString("UnableToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect..
        /// </summary>
        internal static string UnableToConnect {
            get {
                return ResourceManager.GetString("UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0}.
        /// </summary>
        internal static string UnableToConnectTo {
            get {
                return ResourceManager.GetString("UnableToConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application was unable to get access to the private keys of the identity. This typically means the identity has been changed outside of the scope of the app. It can also be a result of a corruption of data. You can try one of two things. Press the Continue button, to continue, without the private keys. You get access to the app, but cannot sign anything. You can then choose to reapply for a new identity from the main menu, with new private keys. You can also try to repair the database, by pressing the R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnableToGetAccessToYourPrivateKeys {
            get {
                return ResourceManager.GetString("UnableToGetAccessToYourPrivateKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open link:.
        /// </summary>
        internal static string UnableToOpenLink {
            get {
                return ResourceManager.GetString("UnableToOpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected response was received..
        /// </summary>
        internal static string UnexpectedResponse {
            get {
                return ResourceManager.GetString("UnexpectedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1}.
        /// </summary>
        internal static string XInY {
            get {
                return ResourceManager.GetString("XInY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating network identity.
        /// </summary>
        internal static string XmppState_Authenticating {
            get {
                return ResourceManager.GetString("XmppState_Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding connection.
        /// </summary>
        internal static string XmppState_Binding {
            get {
                return ResourceManager.GetString("XmppState_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string XmppState_Connected {
            get {
                return ResourceManager.GetString("XmppState_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing connection.
        /// </summary>
        internal static string XmppState_Connecting {
            get {
                return ResourceManager.GetString("XmppState_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string XmppState_Error {
            get {
                return ResourceManager.GetString("XmppState_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching roster.
        /// </summary>
        internal static string XmppState_FetchingRoster {
            get {
                return ResourceManager.GetString("XmppState_FetchingRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string XmppState_Offline {
            get {
                return ResourceManager.GetString("XmppState_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering with broker.
        /// </summary>
        internal static string XmppState_Registering {
            get {
                return ResourceManager.GetString("XmppState_Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting session.
        /// </summary>
        internal static string XmppState_RequestingSession {
            get {
                return ResourceManager.GetString("XmppState_RequestingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting presence.
        /// </summary>
        internal static string XmppState_SettingPresence {
            get {
                return ResourceManager.GetString("XmppState_SettingPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting connection.
        /// </summary>
        internal static string XmppState_StartingEncryption {
            get {
                return ResourceManager.GetString("XmppState_StartingEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiating stream.
        /// </summary>
        internal static string XmppState_StreamNegotiation {
            get {
                return ResourceManager.GetString("XmppState_StreamNegotiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream established.
        /// </summary>
        internal static string XmppState_StreamOpened {
            get {
                return ResourceManager.GetString("XmppState_StreamOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on {1}.
        /// </summary>
        internal static string XOnY {
            get {
                return ResourceManager.GetString("XOnY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to approve to associate your personal information with the identity you review. When third parties review the information in the identity, they will have access to the identity of the reviewers, for transparency..
        /// </summary>
        internal static string YouNeedToApproveToAssociate {
            get {
                return ResourceManager.GetString("YouNeedToApproveToAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to check the box you have carefully reviewed all corresponding information above..
        /// </summary>
        internal static string YouNeedToCheckCarefullyReviewed {
            get {
                return ResourceManager.GetString("YouNeedToCheckCarefullyReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your legal identity.
        /// </summary>
        internal static string YourLegalIdentity {
            get {
                return ResourceManager.GetString("YourLegalIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your legal identity has been marked as compromised. You have therefore been redirected to create a new account..
        /// </summary>
        internal static string YourLegalIdentityHasBeenCompromised {
            get {
                return ResourceManager.GetString("YourLegalIdentityHasBeenCompromised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your legal identity has been marked obsolete. You have therefore been redirected to create a new account..
        /// </summary>
        internal static string YourLegalIdentityHasBeenObsoleted {
            get {
                return ResourceManager.GetString("YourLegalIdentityHasBeenObsoleted", resourceCulture);
            }
        }
    }
}
