..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Languages\AppResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Languages\AppResources.de.resx" -tl de
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Languages\AppResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Languages\AppResources.fr.resx" -tl fr
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Languages\AppResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Languages\AppResources.da.resx" -tl da
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Languages\AppResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Languages\AppResources.no.resx" -tl no
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Languages\AppResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Languages\AppResources.fi.resx" -tl fi
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Languages\AppResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Languages\AppResources.sr.resx" -tl sr
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Languages\AppResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Languages\AppResources.ro.resx" -tl ro
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Languages\AppResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Languages\AppResources.ru.resx" -tl ru


..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Resx\PListResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Resx\PListResources.sv.resx" -tl sv
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Resx\PListResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Resx\PListResources.pt.resx" -tl pt
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Resx\PListResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Resx\PListResources.es.resx" -tl es
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Resx\PListResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Resx\PListResources.de.resx" -tl de
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Resx\PListResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Resx\PListResources.fr.resx" -tl fr
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Resx\PListResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Resx\PListResources.da.resx" -tl da
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Resx\PListResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Resx\PListResources.no.resx" -tl no
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Resx\PListResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Resx\PListResources.fi.resx" -tl fi
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Resx\PListResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Resx\PListResources.sr.resx" -tl sr
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Resx\PListResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Resx\PListResources.ro.resx" -tl ro
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\NeuroAccessMaui" -e -rf "..\NeuroAccessMaui\Resources\Resx\PListResources.resx" -rl en -tf "..\NeuroAccessMaui\Resources\Resx\PListResources.ru.resx" -tl ru

