<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.2.1" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.8" />
    <PackageReference Include="Waher.Content" Version="3.5.0" />
    <PackageReference Include="Waher.Persistence" Version="1.19.0" />
    <PackageReference Include="Waher.Persistence.Files" Version="1.20.1" />
    <PackageReference Include="Waher.Persistence.Serialization.Compiled" Version="1.12.0" />
    <PackageReference Include="Waher.Runtime.Settings" Version="1.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeuroAccess.Nfc\NeuroAccess.Nfc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Include="TestData\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
