name: "Aggregate Changelog"
on:
    pull_request:
        types: [closed]
        branches:
            - dev
jobs:
    update-changelog:
        # Only run on merged PRs whose body contains a Changelog section
        if: ${{ github.event.pull_request.merged && contains(github.event.pull_request.body, 'Changelog') }}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout dev branch
                uses: actions/checkout@v4
                with:
                    ref: dev

            -   name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.x'
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                #add any required pip installs here

            -   name: Write PR body to file
                run: |
                    echo "${{ github.event.pull_request.body }}" > pr_body.txt

            -   name: Extract and prepend changelog entries
                run: |
                    python .github/scripts/prepend_changelog.py \
                    --pr-body-file pr_body.txt \
                    --changelog CHANGELOG.md

            -   name: Commit updated CHANGELOG
                run: |
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"
                    git add CHANGELOG.md
                    git commit -m "chore: update changelog from PR #${{ github.event.pull_request.number }}" || echo "No changes to commit"
                    git push origin dev